title:       A Triangle Jekyll
author:      Leonard Kiyoshi Bogdonoff
linkedin:    http://www.linkedin.com/pub/leonard-bogdonoff/25/14b/8a6
twitter:     rememberlenny
github:      rememberlenny
destination: ./_site
baseurl: /site
markdown: kramdown
include: ['_includes/work']